backend:
  name: git-gateway
  branch: master

media_folder: /static/content/media
public_folder: /media

collections:
  - name: "blog"
    label: "Blog"
    folder: "/static/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
    - label: "blog-post"
      name: "blog-post"
      default: "blog-post"
      widget: object
      fields:
      - { label: "Title", name: "title", widget: string }
      - { label: "Publish Date", name: "date", widget: datetime }
      - { label: "Description", name: "description", widget: string }
      - { label: "Body", name: "body", widget: markdown }
  - name: pages
    label: pages
    editor:
      preview: false
    files:
    - name: home-page
      label: "Home Page"
      file: /static/content/pages/home-page.md
      fields:
      - name: name
        widget: hidden
      - name: projects
        widget: list
        fields:
        - name: project
          widget: object
          label: "project"
          fields:
          - name: title
            widget: string
          - name: images
            widget: list
            fields:
            - name: image
              widget: image
