backend:
  name: git-gateway
  branch: master

media_folder: /static/content/uploads
public_folder: /uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "/static/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: string }
      - { label: "Publish Date", name: "date", widget: datetime }
      - { label: "Description", name: "description", widget: string }
      - { label: "Body", name: "body", widget: markdown }
      - { label: "Image", name: "image", widget: image }
  - label: "Settings"
    name: "settings"
    format: "frontmatter"
    extension: "md"
    editor:
      preview: false
    delete: false
    files:
      - name: "SEO"
        label: "Search Engine Optimization"
        file: /static/content/settings/seo.md
        fields:
          - label: "Open Graph (google, facebook)"
            name: "open-graph"
            widget: "object" 
            fields:
            - { label: "Title", name: "title", widget: "string" }
            - { label: "Description (between 2 and 4 sentences)", name: "description", widget: "string" }
            - { label: "Website URL", name: "url", widget: "string" }
            - { label: "Keywords (comma seperated with no blanks)", name: "keywords", widget: "string" }
            - { label: "Image (ratio approx 1.91:1, min 1200x630px, max 5MB)", name: "image", widget: "image" }

          - label: "Twitter Card Specific"
            name: "twitter"
            widget: "object" 
            fields:
            - { label: "Title (max 70 characters)", name: "title", widget: "string" }
            - { label: "Description (max 200 characters)", name: "description", widget: "string" }
            - { label: "Author", name: "author", widget: "string" }
            - { label: "Twitter Username", name: "user-name", widget: "string", required: false }
            - { label: "Image (ratio 1:1, min 144x144px, max 4096x4096px, 5MB)", name: "image", widget: "image" }

  - label: "Pages"
    name: "pages"
    format: "frontmatter"
    extension: "md"
    editor:
      preview: false
    delete: false
    files:
      - name: "home"
        label: "Home"
        file: /static/content/pages/home.md
        field:
          - label: "Slider"
            name: "slider"
            widget: "list"
            field: { label: "Slide", name: "slide", widget: "image"}
      - name: "about"
        label: "About "
        file: /static/content/pages/about.md
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "body", widget: "markdown" }


